<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>true</UseWindowsForms>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
		<ApplicationIcon>Materials\netreflector_64.ico</ApplicationIcon>
		<Title>.NET Reflector Keygen</Title>
		<Description>Key generator for Redgate .NET Reflector"</Description>
		<Product>.NET Reflector Keygen</Product>
		<Copyright>Copyright © 2023-2025</Copyright>
		<SignAssembly>True</SignAssembly>
	</PropertyGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Properties\RSAKeyValue.xml" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="README.md">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>